### ISSUE TITLE
add 302-redirect for `/http3-explained/`

### ISSUE THREAD

**Issue by ghost** [bagder/daniel.haxx.se#1]
### Problem

the `https://daniel.haxx.se/http3-explained/` is 404.

at first, i wanted to just update all the links in your blog, but for example the page https://daniel.haxx.se/blog/2019/08/05/first-http-3-with-curl/ is not even in the repo?

plus all the older links from around the web, which will be re-surfacing now that google [switched GCP to H/3 by default and firefox got hit by it](https://hacks.mozilla.org/2022/02/retrospective-and-technical-details-on-the-recent-firefox-outage/)

### proposed Solution

add 302-redirect from `/http3-explained/` to `https://http3-explained.haxx.se/`

**Comment by bagder** [comment]
That's a good idea!

**Comment by bagder** [comment]
Thanks

**Comment by ghost** [comment]
np, kinda strange it wasn't part of the initial transition in https://github.com/bagder/daniel.haxx.se/commit/b591ce08d17a85b700452ac540e65140ecd99db7

**Comment by bagder** [comment]
just a silly mistake. I wanted to clean up some leftovers when I moved the site over to a new host, and this was just a little detail I've missed to fix since.
